### ISSUE TITLE
Replace Logo

### ISSUE THREAD

**Issue by ben-nathanson** [pgh-public-meetings/events#6]
We're still using the City Bureau logo; The documentation suggests it would be ideal to use our own branding. I think it would be a fun project to design a new logo, and having our own would help to distinguish between City Bureau and PGH Public Meetings.

**Comment by chamiduu** [comment]
Can I work on this issue?
I can design a simple yet elegant logo and make a PR.

**Comment by ben-nathanson** [comment]
Thanks for asking! Feel free to work on this. 

The City Scrapers will be having a [Meetup](https://www.meetup.com/codeforpgh/events/kpwrwrybcnbdb/) this Friday where I can get some feedback on it if necessary. 

As far as making a pull request, the file that would change is at the path `events/src/logo.png`
